POST http://localhost:3333/habits
Content-Type: application/json

{
  "name": "Beber 2L de água"
}

@habitId = {{createHabit.response.body.id}}

GET http://localhost:3333/habits

PATCH http://localhost:3333/habits/{{habitId}}

DELETE http://localhost:3333/habits/{{habitId}}