# @name createHabit
POST http://localhost:3333/habits
Content-Type: application/json

{
  "name": "Beber 2L de água"
}

###

# Captura o ID da resposta do POST acima
@habitId = {{createHabit.response.body.id}}

### Listar todos os hábitos
GET http://localhost:3333/habits

### Atualizar status usando a variável
PATCH http://localhost:3333/habits/{{habitId}}

### Deletar usando a variável
DELETE http://localhost:3333/habits/{{habitId}}